---
# role: freeradius
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
    role-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      callbacks_enabled: "ansible.builtin.default"
      callback_result_format: "yaml"
      display_ok_hosts: false
      display_skipped_hosts: false
      show_task_path_on_failure: true
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    prepare: "../resources/playbooks/prepare.yml"
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
  inventory:
    group_vars:
      all:
        freeradius_clients:
          - name: "molecule"
            address: "127.0.0.1"
            secret: "molecule-radius-secret-2026"
        freeradius_users:
          - name: "molecule"
            password: "molecule-password"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "side_effect"
    - "converge"
    - "idempotence"
    - "verify"
    - "destroy"
  name: "dev"
platforms:
  - name: "almalinux-latest-freeradius"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "SYS_ADMIN"
    security_opts:
      - "label=disable"
  - name: "debian-latest-freeradius"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "SYS_ADMIN"
    security_opts:
      - "label=disable"
  - name: "fedora-latest-freeradius"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "SYS_ADMIN"
    security_opts:
      - "label=disable"
  - name: "opensuse-leap-latest-freeradius"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "SYS_ADMIN"
    security_opts:
      - "label=disable"
  - name: "opensuse-tumbleweed-latest-freeradius"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "SYS_ADMIN"
    security_opts:
      - "label=disable"
  - name: "ubuntu-latest-freeradius"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "SYS_ADMIN"
    security_opts:
      - "label=disable"
