---
# role: freeradius
# file: molecule/resources/playbooks/converge.yml

- name: FREERADIUS | Converge RADIUS servers with an external database fixture
  hosts: radius_servers
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
  gather_subset:
    - min
